name: Auto-update

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    paths:
      - '.github/workflows/auto-update.yml'
  schedule: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '* 6,10,14,18 * * *'
jobs:
  update-sources:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          # extra_nix_config: |
          #   trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          #   substituters = https://hydra.iohk.io https://cache.nixos.org/
      - run: nix flake update

      - name: Commit updated flake
        env:
          GITHUB_JOB: ${{ env.GITHUB_JOB }}
          GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
        run: |
          git config --global user.name 'UpdateBot'
          git config --global user.email 'superherointj@users.noreply.github.com'
          [ ! -z "$(git status --porcelain)" ] && (git add flake.lock; git commit -m "flake.lock updated"; git push) || echo "Nothing to commit."

##################################

# git checkout -b "auto-update-sources-$GITHUB_RUN_ID"
# --set-upstream origin "auto-update-sources-$GITHUB_RUN_ID"

# - name: Open pull request
#   uses: repo-sync/pull-request@v2
#   env:
#     GITHUB_JOB: ${{ env.GITHUB_JOB }}
#     GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
#   with:
#     destination_branch: "main"
#     source_branch: auto-update-sources-${{ github.run_id }}
#     pr_title: "Update sources"
#     pr_body: ":robot_face: Updating sources to the latest version.\n${{steps.update-sources.outputs.result}}"
#     pr_reviewer: "superherointj"
#     pr_assignee: "superherointj"
#     github_token: ${{ secrets.GH_PAT_INTJ }}

# - name: "Update sources"
#   uses: actions/github-script@v6
#   id: update-sources
#   with:
#     result-encoding: string
#     script: |
#       const script = require('./.github/workflows/auto-update.js')
#       return await script({github, context, core, require})
